import Tabbar from './tabbar.js';
import Login from './Auth/Login'
import ExampleLogin from './Auth/ExampleLogin';
import ExampleSignUp from './Auth/ExampleSignUp';
import SignUp from './Auth/SignUp';
import Logout from './Auth/Logout';
import phoneCode from './Auth/phoneCode';
import Home from './Home/Home';
import Profile from './Profile/profile';
import Orders from './Profile/Order/Orders';
import Cart from './Profile/Carts/Cart';
import PaymentProducts from './Payments/PaymentProducts.js';
import PaymentFtPtDt from './Payments/PaymentFtPtDt.js';
import PaymentSports from './Payments/PaymentSports.js';
import PaymentMethods from './Profile/PaymentMethod/PaymentMethods.js'
import AddCreditCardPage from './Profile/PaymentMethod/AddCreditCardPage.js';
import AddCardsNextPage from './Profile/PaymentMethod/AddCardsNextPage.js';
import Adresses from './Profile/Adress/AdressesPage.js';
import AddAdressPage from './Profile/Adress/AddAdressPage.js';
import FavoriteProducts from './Profile/FavoriteProduct/FavoriteProducts.js';
import ContactPreferences from './Profile/ContactPreference/ContactPreferences.js';
import AccountSettings from './Profile/AccountSetting/AccountSettings.js';
import Help from './Profile/Helps/Help.js';
import Languages from './Profile/Language/Languages.js';
import Products from './Products/ProductsCategoryPage.js';
import ProductDetailPage from './Products/ProductDetailPage.js';
import ProductsItems from './Products/ProductsItemsPage.js';
import QrCode from './Qrcode/QrcodeHome.js';
import QrCodePage from './Qrcode/QrCodePage.js'
import Budy from './Budy/budy.js';
import PtDtitemPages from './Budy/PtDtChPages/PtDtitemPages.js';
import ChallengeDetailPage from './Budy/ChallengePage/ChallengeDetailPage.js';
import ChallengePage from './Budy/ChallengePage/ChallengeePage.js';
import AllItemAllPages from './F,F-ItemsPages/AllItemAllPages.js';
import ItemPackagePage from './F,F-ItemsPages/AllItemPacketsPages.js';
import Sports from './Home/Sports/SportsCategoryPage.js';
import PackageDetailPage from './Home/Fitness/FitnessPackageDetailPage.js';
import MyEventPage from './Qrcode/MyPages/MyEventPage.js';
import MyEventDetailPage from './Qrcode/MyPages/MyEventDetailPage.js';